DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS sessions;
CREATE TABLE IF NOT EXISTS posts (id INTEGER PRIMARY KEY, date TEXT, title TEXT,content TEXT);
CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY,user TEXT, expiry INTEGER, session_token TEXT);
